FROM jupyter/scipy-notebook

MAINTAINER Jeremy Diaz <jeremy.diaz@colorado.edu>

RUN pip install --upgrade pip

RUN pip install nltk gensim

RUN git clone https://github.com/jdiaz4302/ML_Workshop_Series.git
